apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-sca-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-sca-app
  template:
    metadata:
      labels:
        app: static-sca-app
    spec:
      containers:
        - name: static-sca
          image: static-sca-sandbox:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: static-sca-app
spec:
  type: ClusterIP
  selector:
    app: static-sca-app
  ports:
    - port: 3001
      targetPort: 3001
